<a href="https://colab.research.google.com/github/map72ru/python_data_lib/blob/main/Lesson_2%2B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Задание на повторение материала

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [ ]:
import numpy as np

a = np.linspace(12, 24, 12, endpoint=False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [ ]:
a1=a.reshape(2, 6)
a2=a.reshape(6, 2)
a3=a.reshape(3, 4)
a4=a.reshape(4, 3)
a5=a.reshape(12, 1)

print('a1', a1)
print('a2', a2)
print('a3', a3)
print('a4', a4)
print('a5', a5)

a1 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
a2 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
a3 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
a4 [[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
a5 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [ ]:
a1=a.reshape(2, -1)
a2=a.reshape(6, -1)
a3=a.reshape(3, -1)
a4=a.reshape(-1, 3)
a5=a.reshape(-1, 1)

print('a1', a1)
print('a2', a2)
print('a3', a3)
print('a4', a4)
print('a5', a5)

a1 [[12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
a2 [[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]
a3 [[12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
a4 [[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
a5 [[12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


In [ ]:
print('Нет, это будет двухмерный массив')

Нет, это будет двухмерный массив


Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [ ]:
rd = np.random.default_rng()
f = rd.normal(0, 1.0, size=(3, 4))
print('random array[3,4] = ', f)
r = f.reshape(f.size)
print('random array[12] = ', r)
print('Mean=', np.mean(r))
print('Sigma=', np.std(r, ddof=1))

random array[3,4] =  [[ 0.74527844  0.4743249   0.29661944  0.53516889]
 [ 0.10973701 -0.08243236 -1.41496082 -0.41033566]
 [ 0.67349182  0.21659035  0.02495382  0.02042963]]
random array[12] =  [ 0.74527844  0.4743249   0.29661944  0.53516889  0.10973701 -0.08243236
 -1.41496082 -0.41033566  0.67349182  0.21659035  0.02495382  0.02042963]
Mean= 0.09907212196439058
Sigma= 0.5821511004573393


Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [ ]:
a = np.linspace(20, 0, 10, endpoint=False, retstep=2, dtype=int)
a

(array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2]), -2.0)

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [ ]:
b = np.linspace(start=[20], stop=[1], num=10, endpoint=False, retstep=False, dtype=int, axis=0)
print(b)
print(' a это одномерный массив, в - двухмерный, разное количество элементов')

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]
 a это одномерный массив, в - двухмерный, разное количество элементов


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [ ]:
a = np.zeros((4, 4))
b = np.zeros((5, 4))+1
c = np.vstack((a, b))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [ ]:
a = np.arange(0, 12, dtype=int)
A = a.reshape(4, 3)
print('A=', A)
At = np.transpose(A)
B = np.dot(A, At)
print('B=', B)
print('Size=', B.shape)

Bi = np.linalg.inv(B)
print('Bi=', Bi)

A= [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B= [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Size= (4, 4)


LinAlgError: ignored

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [ ]:
rd = np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [ ]:
a = np.random.randint(0, 16, 16)
a

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])